# "app" specifies the runtime and entry point of your Lambda function.
app: slack-agile-poker-bot
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dinushab14
# "service" is the name of this project. This will also be added to your AWS resource names.
service: slack-agile-poker-bot

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SLACK_SIGNING_SECRET: ${ssm:/slack-signing-secret}
    SCRUM_POKER_TABLE_NAME: ${self:service}-scrum-poker-table
    SLACK_BOT_TOKEN: ${ssm:/slack-bot-token}
    SLACK_API_BASE_URL: https://slack.com/api
    SLACK_PARTICIPANTS_TOPIC_ARN:
      Ref: ScrumPokerParticipantsTopic
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            Ref: ScrumPokerParticipantsTopic
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:TransactWriteItems
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.SCRUM_POKER_TABLE_NAME}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.SCRUM_POKER_TABLE_NAME}/index/*

functions:
  commands:
    handler: dist/commands/handler.handler
    events:
      - httpApi:
          path: /slack/commands
          method: post
  interactions:
    handler: dist/interactions/handler.handler
    events:
      - httpApi:
          path: /slack/interactions
          method: post
  worker:
    handler: dist/worker/handler.handler
    events:
      - sns:
          arn:
            Ref: ScrumPokerParticipantsTopic
          topicName: scrum-poker-participants-topic

resources:
  Resources:
    ScrumPokerParticipantsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: scrum-poker-participants-topic
    ScrumPokerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SCRUM_POKER_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE


