# "app" specifies the runtime and entry point of your Lambda function.
app: slack-agile-poker-bot
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dinushab14
# "service" is the name of this project. This will also be added to your AWS resource names.
service: slack-agile-poker-bot

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource:
            - Fn::GetAtt: [SlackIngressQueue, Arn]
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:TransactWriteItems
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:functions.worker.environment.SCRUM_POKER_TABLE_NAME}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:functions.worker.environment.SCRUM_POKER_TABLE_NAME}/index/*

functions:
  ingress:
    handler: dist/handlers/ingress.handler
    environment:
      SLACK_SIGNING_SECRET: ${ssm:/slack-signing-secret}
      SLACK_INGRESS_QUEUE_URL:
        Ref: SlackIngressQueue
    events:
      - httpApi:
          path: /slack/commands
          method: post
  worker:
    handler: dist/handlers/worker.handler
    environment:
      SCRUM_POKER_TABLE_NAME: ${self:service}-scrum-poker-table
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SlackIngressQueue, Arn]
          batchSize: 10
          maximumBatchingWindow: 30

resources:
  Resources:
    SlackIngressQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: slack-ingress-queue
        VisibilityTimeout: 30
        MessageRetentionPeriod: 345600 # 4 days in seconds
    ScrumPokerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:functions.worker.environment.SCRUM_POKER_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE


